sudo: false
language: node_js
script: npm test
node_js:
- '4'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_deploy:
- npm-prepublish --verbose
deploy:
  provider: npm
  email: wheresrhys@gmail.com
  api_key:
    secure: CdQkA4gLU7yAEnSAGcWtf7PdRf/WSJc/UkX94KfLyx3xv0KGREWhWqD4yZok4ay6N039lpXaBOq3ZJJ0XKKrKOW9em5CL2rP0NGgEbOMSk53Yk+tJya9mi3Ni2mZTfNhoOIpSj6Qja0M2uF4/+UnwlKzruu0tbDd1u/vHkssniI=
  on:
    all_branches: true
    tags: true
    repo: wheresrhys/fetch-mock
