sudo: false
language: node_js
script: npm test
node_js:
- '4'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g bower
- bower install
before_deploy:
- npm-prepublish --verbose
deploy:
  provider: npm
  email: wheresrhys@gmail.com
  api_key:
    secure: VzENYjzeS/EG6FKLGzapkYij22gCI8x8FPypp2u/9i/e+MZVI0V9AXWGuTu+M8ZObt3j5/VW9jKbc2ns8+Zc/8qZKUQUsVWHwB951IfQD/vZ6w2RHe+fEs8UAAsKhRW+69cy4MLzS7jc6oX+ZkdRUfpkrmxl16tILGFN4AeesgA=
  on:
    all_branches: true
    tags: true
    repo: wheresrhys/fetch-mock
