# ----
# Site

title: fetch-mock
description: Mock http requets using fetch
url: https://www.wheresrhys.co.uk/fetch-mock-docs-workspace
google_analytics_key:
permalink: pretty

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: General documentation
    position: 1
  api:
    title: API documentation
    position: 2
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "general"
    values:
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  javascript: JavaScript

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
